name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOKERHUB_USER}}
          password: ${{secrets.DOKERHUB_PWD}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            jamesfrj/kube-news:latest
            jamesfrj/kube-news:${{github.run_number}}
